version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:11.12.0
      - image: mongo:4.0.3
    steps:
      - checkout
      - run: yarn install
      - run: yarn test:server
      - run: yarn test:client
